In [1]:
import numpy
numpy.__version__

'1.18.5'

In [3]:
import numpy as np

Numpy is a python Library. It is used for working with array. It maked processing faster and the numpy arrays are called ndarray(n-dimensional array).
Numpy Stands for Numerical Python. 

Numpy brings the power of matlabs in python


In [4]:
#creating arrays from python list
a=[1,2,3,4,5]
np.array(a)

array([1, 2, 3, 4, 5])

In [5]:
#array elements should of same datatypes or else it will typecast to higher datatype if thats possible
b=[1,2,3.3,4,5,6]
np.array(b)

array([1. , 2. , 3.3, 4. , 5. , 6. ])

In [6]:
#creating two dimensional array
c=[[1,2,3,4],
  [5,6,7,8]]
np.array(c)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
#creating ones and zeros array like we do in Matlab
np.zeros((3,6),dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
#to create array with a constant
np.full((2,3),1.6)

array([[1.6, 1.6, 1.6],
       [1.6, 1.6, 1.6]])

In [22]:
#seed for reporducibiltiy
np.random.seed(0)
x1=np.random.randint(10,size=6)
x1

array([5, 0, 3, 3, 7, 9])

In [26]:
#random 2D array
x2=np.random.randint(2,10,size=(3,5))
x2

array([[2, 4, 5, 2, 3],
       [5, 7, 5, 5, 8],
       [9, 2, 3, 3, 3]])

In [30]:
#random 3D array
x3=np.random.randint(3,11,size=(3,2,5))
x3

array([[[10,  7,  6,  7,  7],
        [ 7,  3,  9, 10,  7]],

       [[ 6,  5, 10, 10,  8],
        [ 8,  8,  3,  4,  8]],

       [[ 4,  6,  3, 10,  8],
        [ 9,  3,  4,  5,  7]]])

In [32]:
#Numpy Attributes
print("x3 ndim:",x3.ndim) #no of dimension
print("x3 shape:",x3.shape) #size of each dimension
print("x3 size:",x3.size) #total size of array

x3 ndim: 3
x3 shape: (3, 2, 5)
x3 size: 30


In [33]:
#datatype of array
print("dtype:", x3.dtype)

dtype: int32


In [41]:
#Accessing Elements in numpy
print(x1[3])
print(x2[2,3])
print(x3[2,1,3])
print(x3[2,1,-1]) #accesing last element using -1




3
3
5
7


In [46]:
#Array Slicing
x4=np.arange(20) #range of values
x4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:

x5=np.arange(0,20,2)
x5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [50]:
x5[:5] #first five elements

array([0, 2, 4, 6, 8])

In [52]:
x5[5:]#lst five elements

array([10, 12, 14, 16, 18])

In [55]:
x5[4:8]# values in between

array([ 8, 10, 12, 14])

In [57]:
x5[::3]#slicing evert third element

array([ 0,  6, 12, 18])

In [59]:
x5[4::3] #starting from 4th index every third element

array([ 8, 14])

In [60]:
#slicing in mutlidimensional array

In [64]:
x6=np.random.randint(5,size=(5,5))
x6

array([[1, 2, 1, 4, 2],
       [3, 0, 3, 2, 3],
       [0, 0, 0, 3, 2],
       [3, 0, 4, 0, 0],
       [2, 3, 2, 3, 0]])

In [69]:
#slicing bottom two rows
x6[3:,:]


array([[3, 0, 4, 0, 0],
       [2, 3, 2, 3, 0]])

In [70]:
#slicing lst three cols
x6[:,2:]

array([[1, 4, 2],
       [3, 2, 3],
       [0, 3, 2],
       [4, 0, 0],
       [2, 3, 0]])

In [81]:
#revesing rows and columns
print(x6)
print(x6[::-1,::-1])


[[1 2 1 4 2]
 [3 0 3 2 3]
 [0 0 0 3 2]
 [3 0 4 0 0]
 [2 3 2 3 0]]
[[0 3 2 3 2]
 [0 0 4 0 3]
 [2 3 0 0 0]
 [3 2 3 0 3]
 [2 4 1 2 1]]


In [82]:
#accesing a whole row or column
print(x6[:,2])
print(x6[3,:])


[1 3 0 4 2]
[3 0 4 0 0]


In [84]:
#slicing creates views and not copies.
x7=x6[:2,:2]
print(x7)

[[1 2]
 [3 0]]


In [85]:
x7[0,0]=25

In [87]:
#see changing in x7 changed x6 also hence we use copy command to copy to avoid this problem
x6

array([[25,  2,  1,  4,  2],
       [ 3,  0,  3,  2,  3],
       [ 0,  0,  0,  3,  2],
       [ 3,  0,  4,  0,  0],
       [ 2,  3,  2,  3,  0]])

In [88]:
x8=x6[:3,:3].copy()
x8

array([[25,  2,  1],
       [ 3,  0,  3],
       [ 0,  0,  0]])

In [89]:
x8[0,0]=99
x8

array([[99,  2,  1],
       [ 3,  0,  3],
       [ 0,  0,  0]])

In [91]:
x6 # we created copy of x8 hence it has not affected x6

array([[25,  2,  1,  4,  2],
       [ 3,  0,  3,  2,  3],
       [ 0,  0,  0,  3,  2],
       [ 3,  0,  4,  0,  0],
       [ 2,  3,  2,  3,  0]])

In [108]:
#Reshaping of Arrays

x9=x8.reshape((1,9))
x9


array([[99,  2,  1,  3,  0,  3,  0,  0,  0]])

In [102]:
x10=x8.reshape((9,1))
x10

array([[99],
       [ 2],
       [ 1],
       [ 3],
       [ 0],
       [ 3],
       [ 0],
       [ 0],
       [ 0]])

In [113]:
#Array Concatenation and Splitting
x11=np.array([1,2,3])
x12=np.array([4,5,6])
np.concatenate([x11,x12])

array([1, 2, 3, 4, 5, 6])

In [114]:
grid = np.array([[1, 2, 3],[4, 5, 6]])# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [118]:
#For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:

x13=np.vstack([x8,grid])
x13

array([[99,  2,  1],
       [ 3,  0,  3],
       [ 0,  0,  0],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [120]:
x14=np.hstack([x8,x2])
x14

array([[99,  2,  1,  2,  4,  5,  2,  3],
       [ 3,  0,  3,  5,  7,  5,  5,  8],
       [ 0,  0,  0,  9,  2,  3,  3,  3]])

In [131]:
#Splitting

x15,x16,x17=np.split(x14,3)

In [132]:
x15

array([[99,  2,  1,  2,  4,  5,  2,  3]])

In [133]:
x16

array([[3, 0, 3, 5, 7, 5, 5, 8]])

In [135]:
x17

array([[0, 0, 0, 9, 2, 3, 3, 3]])

In [136]:
x18,x19=np.split(x14,2,axis=1)

In [138]:
x18

array([[99,  2,  1,  2],
       [ 3,  0,  3,  5],
       [ 0,  0,  0,  9]])

In [139]:
x19

array([[4, 5, 2, 3],
       [7, 5, 5, 8],
       [2, 3, 3, 3]])

In [157]:
upper, lower = np.vsplit(x14, [2])

In [158]:
upper

array([[99,  2,  1,  2,  4,  5,  2,  3],
       [ 3,  0,  3,  5,  7,  5,  5,  8]])

In [159]:
lower

array([[0, 0, 0, 9, 2, 3, 3, 3]])

In [144]:
left, right = np.hsplit(x14, [3])
print(left)
print(right)

[[99  2  1]
 [ 3  0  3]
 [ 0  0  0]]
[[2 4 5 2 3]
 [5 7 5 5 8]
 [9 2 3 3 3]]
